name = "RFCish"
license = "MIT"
licenselink = "https://github.com/6r3g/hugo-theme-rfcish/LICENSE"
description = "Simple theme heavily inspired by RFCs"

# The home page of the theme, where the source can be found
homepage = "https://github.com/6r3g/hugo-theme-rfcish"

# If you have a running demo of the theme
#demosite = 'https://owner.github.io/repo'

# If the theme has a single author
[author]
  name = '6r3g'
  homepage = 'https://6r3g.github.io'

# If porting an existing theme
[original]
  author = 'AngeloR'
  homepage = 'https://xangelo.ca/'
  repo = 'https://github.com/AngeloR/plain-hugo-theme'
