baseURL = "/"
languageCode = "en"
theme = 'hugo-theme-rfcish'
Copyright = "&copy; 2025 "
enableEmoji = true
DefaultContentLanguage = "en"

[params]
author = "Author"
description = "Clean and simple blog"
favicon = "/img/favicon.ico"
mainSections = "posts" # Only list posts on home
ShowThemeInfo = true
toc = false # Default no ToC, declare "toc: true" in post for override

[languages]
  [languages.en]
    title = "RFCish demo"
  [languages.en.params]
    subtitle = "Hi everyone :wave: ! Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut tempore et dolore vero eos et accusamus corrupti quos dolores mollitia animi est."
    languageName = "en"
    weight = 1
  [languages.fr]
    title = "RFCish demo"
  [languages.fr.params]
    subtitle = "Hi everyone :wave: ! Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut tempore et dolore vero eos et accusamus corrupti quos dolores mollitia animi est."
    languageName = "fr"
    weight = 2

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.extensions.extras.delete]
    enable = true
  [markup.goldmark.extensions.extras.insert]
    enable = true
  [markup.goldmark.extensions.extras.mark]
    enable = true
  [markup.goldmark.extensions.extras.subscript]
    enable = true
  [markup.goldmark.extensions.extras.superscript]
    enable = true
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 6 # ToC ends at H6
		ordered = true # generates <ul> instead of <ol>

[pagination]
pagersize = 20

[menus]
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 10
  [[menus.main]]
    name = 'Notes'
    pageRef = '/notes'
    weight = 20
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 30